### ISSUE TITLE
i40e pfring stops receing packets.

### ISSUE THREAD

**Issue by papage** [ntop/PF_RING#423] opened 2018-11-02 14:10 UTC
Hi all,

Can anyone explain the following behaviour? It seems to be a bug.
I have an i40e passthroughed to a VM, with ntop installed. I can't see any traffic on the interface, but when i change something on the interface (ex the MTU), traffic starts to flow and after sometime, it stops again.
A few clues about my setup is:
- Dell R740 with XL710 4port 10G adapter.
- Proxmox installed on host, with SRIOV enabled
-  4 VFs configures on one of the  XL710 ports
-  XL710 port is connected to a SPAN port on a switch, receiving traffic via vlan1800
- VF is assigned vlan1800 and trust=on
- VM kernel is: Linux lts16 4.4.0-131
- i40evf is the driver of the card in the VM.
i40evf: Intel(R) 40-10 Gigabit Virtual Function Network Driver - version 3.6.10
- Even if without VFs (passing through the native PF), the problem is the same.
- The problem is solved when I poke something with ethtool or ifconfig (PF settings and not IP addresses ). For example:
 "ifconfig ens16 mtu 9000"
"ethtool -G ens16f1 rx 2048 tx 2048"

Thanx,
Spiros

```
root@lts16:~/.ssh# pfcount -i ens16
Using PF_RING v.7.2.0
Capturing from ens16 [mac: 3C:FD:FE:99:99:13][if_index: 5][speed: 0Mb/s]
# Device RX channels: 4
# Polling threads:    1
Dumping statistics on /proc/net/pf_ring/stats/24791-ens16.24
=========================
Absolute Stats: [0 pkts total][0 pkts dropped][0.0% dropped]
[0 pkts rcvd][0 bytes rcvd]
=========================

=========================
Absolute Stats: [0 pkts total][0 pkts dropped][0.0% dropped]
[0 pkts rcvd][0 bytes rcvd][0.00 pkt/sec][0.00 Mbit/sec]
=========================
Actual Stats: [0 pkts rcvd][1'000.32 ms][0.00 pps][0.00 Gbps]
=========================

=========================
Absolute Stats: [0 pkts total][0 pkts dropped][0.0% dropped]
[0 pkts rcvd][0 bytes rcvd][0.00 pkt/sec][0.00 Mbit/sec]
=========================
Actual Stats: [0 pkts rcvd][1'000.28 ms][0.00 pps][0.00 Gbps]
=========================

=========================
Absolute Stats: [0 pkts total][0 pkts dropped][0.0% dropped]
[0 pkts rcvd][0 bytes rcvd][0.00 pkt/sec][0.00 Mbit/sec]
=========================
Actual Stats: [0 pkts rcvd][1'000.17 ms][0.00 pps][0.00 Gbps]
=========================
#################################################################
## **HERE I DO a "ifconfig ens16 mtu 8900" to  change the MTU, fro another shell** ####
################################################################
=========================
Absolute Stats: [412'645 pkts total][0 pkts dropped][0.0% dropped]
[412'645 pkts rcvd][367'358'813 bytes rcvd][37'503.29 pkt/sec][267.10 Mbit/sec]
=========================
Actual Stats: [412'645 pkts rcvd][1'000.15 ms][412'580.63 pps][2.94 Gbps]
=========================

=========================
Absolute Stats: [983'096 pkts total][0 pkts dropped][0.0% dropped]
[983'096 pkts rcvd][869'204'719 bytes rcvd][81'904.04 pkt/sec][579.32 Mbit/sec]
=========================
Actual Stats: [570'451 pkts rcvd][1'000.12 ms][570'380.84 pps][4.01 Gbps]
=========================

=========================
Absolute Stats: [1'523'493 pkts total][0 pkts dropped][0.0% dropped]
[1'523'493 pkts rcvd][1'343'742'276 bytes rcvd][117'163.56 pkt/sec][826.72 Mbit/sec]
=========================
Actual Stats: [540'397 pkts rcvd][1'000.10 ms][540'339.18 pps][3.80 Gbps]
=========================

=========================
Absolute Stats: [2'097'129 pkts total][0 pkts dropped][0.0% dropped]
[2'097'129 pkts rcvd][1'852'821'532 bytes rcvd][149'759.86 pkt/sec][1'058.50 Mbit/sec]
=========================
Actual Stats: [573'636 pkts rcvd][1'000.14 ms][573'550.54 pps][4.07 Gbps]
=========================

=========================
Absolute Stats: [2'721'927 pkts total][0 pkts dropped][0.0% dropped]
[2'721'927 pkts rcvd][2'409'625'187 bytes rcvd][181'419.28 pkt/sec][1'284.83 Mbit/sec]
=========================
Actual Stats: [624'798 pkts rcvd][1'000.23 ms][624'649.95 pps][4.45 Gbps]
=========================

=========================
Absolute Stats: [3'281'245 pkts total][0 pkts dropped][0.0% dropped]
[3'281'245 pkts rcvd][2'905'175'066 bytes rcvd][205'030.82 pkt/sec][1'452.25 Mbit/sec]
=========================
Actual Stats: [559'318 pkts rcvd][1'000.15 ms][559'232.99 pps][3.96 Gbps]
=========================

^CLeaving...
=========================
Absolute Stats: [3'449'890 pkts total][0 pkts dropped][0.0% dropped]
[3'449'890 pkts rcvd][3'058'078'560 bytes rcvd][211'759.09 pkt/sec][1'501.67 Mbit/sec]
=========================
Actual Stats: [168'645 pkts rcvd][287.91 ms][585'751.89 pps][4.25 Gbps]
```

**Comment by cardigliano** [comment] 2018-11-02 15:00
Hi @papage, this does not look like a PF_RING issue, it seems that the pf_ring kernel module is not  receiving any packet from the card / driver until you change the MTU (btw, what is the correct MTU on the link you are monitoring?)

**Comment by papage** [comment] 2018-11-02 15:12
Hi Cardigliano,

The correct MTU is 9000 but the packets come from an internet service, so their max size are 1500 bytes.

The problem is very strange, since the card/driver is the XL710, which i assume is very common and somebody else might come by the same problem. The driver is also the latest one. Perhaps I need to update the adapter firmware.

Sp

**Comment by cardigliano** [comment] 2018-11-02 15:15
@papage I would definitely update the firmware if there is an upgrade available, and the driver (Intel drivers are available at https://sourceforge.net/projects/e1000/files/). I never experienced a similar issue.

**Comment by papage** [comment] 2018-11-03 08:33
Thanx for the answer. 
Just to let you know, I updated the firmware and used the latest driver, but the issue remains...

**Comment by cardigliano** [comment] 2018-11-15 08:37
@papage did you check if you are able to reproduce the same with tcpdump?

**Comment by papage** [comment] 2018-11-15 09:50
Yes, it is fully replicated with tcpdump. 
If I put the interface to promiscious mode and i do "ifconfig", the missing packets appear as "dropped packets".  

Further troubleshooting I have done, showed that if I have configured 6 queues on the interface, after sometime, one queue stops RXing packets. These packets that are received by the particular queue appear as "dropped" in ifconfig.  As time passes by, each queue stops RXing packets, until they all stop.

If i do anything that reconfigures the card (change the MTU, queues ), the packets start to appear and all queues resume RXing packets.

I don't think it is a pfring issue. It might be a hardware issue even though it seems to be as a "soft" issue.

I am troubleshooting this issue with Dell and I have also posted a message to an Intel forum.

If I have any more info I will update you. Meanwhile, I am open to any ideas....

Sp

**Comment by cardigliano** [comment] 2018-11-15 09:52
@papage thank you for the update, to be honest I do not have ideas sorry, I never experienced a similar issue. Since this is not related to pf_ring I will close this ticket. Thank you.

**Closed as completed by cardigliano** 2018-11-15 09:52 UTC

**Comment by teoring** [comment] 2019-12-18 13:36
> Yes, it is fully replicated with tcpdump.
> If I put the interface to promiscious mode and i do "ifconfig", the missing packets appear as "dropped packets".
> 
> Further troubleshooting I have done, showed that if I have configured 6 queues on the interface, after sometime, one queue stops RXing packets. These packets that are received by the particular queue appear as "dropped" in ifconfig. As time passes by, each queue stops RXing packets, until they all stop.
> 
> If i do anything that reconfigures the card (change the MTU, queues ), the packets start to appear and all queues resume RXing packets.
> 
> I don't think it is a pfring issue. It might be a hardware issue even though it seems to be as a "soft" issue.
> 
> I am troubleshooting this issue with Dell and I have also posted a message to an Intel forum.
> 
> If I have any more info I will update you. Meanwhile, I am open to any ideas....
> 
> Sp

Have you found the reason of the problem and solution?
