### ISSUE TITLE
snort IPS (drop rule ) not droping traffic

### ISSUE THREAD

**Issue by dotanalon** [ntop/PF_RING#427] opened 2018-11-14 18:11 UTC
I configured snort 2.9.12 and pf_ring ft 7.2 (ndpi 2.4-stable) in IPS mode:
PF_RING_FT_CONF=/etc/pf_ring/ft-rules.conf snort -c /etc/snort/snort.conf -l /var/log/snort/ --daq-dir=/usr/local/lib/daq --daq pfring --daq-mode inline -Q -i ens5:ens6 --daq-var fast-tx=1 --daq-var clusterid=10,11 --daq-var bindcpu=1 -A console

root@ip-172-16-3-216:~# cat /etc/pf_ring/ft-rules.conf
[shunt]
default = 10
tcp = 6

[filter]
ICMP = discard

I can see in the console that snort try to drop some traffic:
11/14-18:10:12.376018  [Drop] [**] [1:666:0] reject any icmp [**] [Priority: 0] {ICMP} 10.0.0.10 -> 8.8.4.4
11/14-18:10:12.384264  [Drop] [**] [1:666:0] reject any icmp [**] [Priority: 0] {ICMP} 8.8.4.4 -> 172.16.57.247
11/14-18:10:13.377417  [Drop] [**] [1:666:0] reject any icmp [**] [Priority: 0] {ICMP} 10.0.0.10 -> 8.8.4.4
11/14-18:10:13.385309  [Drop] [**] [1:666:0] reject any icmp [**] [Priority: 0] {ICMP} 8.8.4.4 -> 172.16.57.247
11/14-18:10:14.378472  [Drop] [**] [1:666:0] reject any icmp [**] [Priority: 0] {ICMP} 10.0.0.10 -> 8.8.4.4

snort rule:
ubuntu@ip-172-16-3-216:~/snort_src/nDPI$ cat /etc/snort/rules/1.rules 
reject icmp any any <> any any ( msg:"reject any icmp"; sid:666; )
reject tcp any any <> any 80 ( msg:"reject any http"; sid:6666; )

and in dmesg log:
[11432.893139] [PF_RING] handle_sw_filtering_hash_bucket:3064 Duplicate found (rule_id=0) while adding rule (rule_id=2): discarded
[11432.893166] [PF_RING] handle_sw_filtering_hash_bucket:3064 Duplicate found (rule_id=1) while adding rule (rule_id=3): discarded
[11433.893339] [PF_RING] handle_sw_filtering_hash_bucket:3064 Duplicate found (rule_id=0) while adding rule (rule_id=4): discarded
[11433.893377] [PF_RING] handle_sw_filtering_hash_bucket:3064 Duplicate found (rule_id=1) while adding rule (rule_id=5): discarded
[11434.893558] [PF_RING] handle_sw_filtering_hash_bucket:3064 Duplicate found (rule_id=0) while adding rule (rule_id=6): discarded
[11434.893600] [PF_RING] handle_sw_filtering_hash_bucket:3064 Duplicate found (rule_id=1) while adding rule (rule_id=7): discarded
[11435.893776] [PF_RING] handle_sw_filtering_hash_bucket:3064 Duplicate found (rule_id=0) while adding rule (rule_id=8): discarded
[11435.893812] [PF_RING] handle_sw_filtering_hash_bucket:3064 Duplicate found (rule_id=1) while adding rule (rule_id=9): discarded
[11436.894023] [PF_RING] handle_sw_filtering_hash_bucket:3064 Duplicate found (rule_id=0) while adding rule (rule_id=10): discarded
[11436.894067] [PF_RING] handle_sw_filtering_hash_bucket:3064 Duplicate found (rule_id=1) while adding rule (rule_id=11): discarded
[11437.894241] [PF_RING] handle_sw_filtering_hash_bucket:3064 Duplicate found (rule_id=0) while adding rule (rule_id=12): discarded
[11437.894272] [PF_RING] handle_sw_filtering_hash_bucket:3064 Duplicate found (rule_id=1) while adding rule (rule_id=13): discarded
[11438.894482] [PF_RING] handle_sw_filtering_hash_bucket:3064 Duplicate found (rule_id=0) while adding rule (rule_id=14): discarded
[11438.894518] [PF_RING] handle_sw_filtering_hash_bucket:3064 Duplicate found (rule_id=1) while adding rule (rule_id=15): discarded
[11439.894701] [PF_RING] handle_sw_filtering_hash_bucket:3064 Duplicate found (rule_id=1) while adding rule (rule_id=16): discarded
[11439.894736] [PF_RING] handle_sw_filtering_hash_bucket:3064 Duplicate found (rule_id=0) while adding rule (rule_id=17): discarded
[11440.894927] [PF_RING] handle_sw_filtering_hash_bucket:3064 Duplicate found (rule_id=0) while adding rule (rule_id=18): discarded
[11440.894959] [PF_RING] handle_sw_filtering_hash_bucket:3064 Duplicate found (rule_id=1) while adding rule (rule_id=19): discarded

**Comment by dotanalon** [comment] 2018-11-15 07:03
[syslog.gz](https://github.com/ntop/PF_RING/files/2583993/syslog.gz)
I reloaded pf_ring.ko with higher debug level and rerun the scenario,
please see the attached syslog file
Thanks

**Comment by cardigliano** [comment] 2018-11-20 09:40
@dotanalon it seems you can safely ignore those warning (you should no longer see them if you update to latest code, they have been moved to  debug level 1 now), it happens when snort inserts multiple rules for the same tuple.

**Comment by dotanalon** [comment] 2018-11-20 14:25
@cardigliano, I dont have issue with the warnings.. I have issue with the fact that snort instruct drop action and pf_ring dont drop the traffic... I added the warnings as debug info for the issue (snort and pf_ring integration dont work)
Thanks,

**Comment by cardigliano** [comment] 2018-11-20 17:34
@dotanalon I noticed that the filtering api in snort was missing some new field, I recommend you to update both the library (recompile the daq) and the pf_ring kernel module (I pushed some patch). Please let me know, thank you.

**Comment by dotanalon** [comment] 2018-11-20 17:59
@cardigliano need to recompile snort and nDPI also?

**Comment by cardigliano** [comment] 2018-11-20 18:01
You do not need to recompile Snort, the DAQ is enough. You need to recompile nDPI yes, to make sure it is in sync with PF_RING.

**Comment by dotanalon** [comment] 2018-11-20 18:27
@cardigliano 
I recompiled the following:
* pf_ring kernel (kernel folder)
* pf_ring lib (userland/lib folder)
* pf_ring  snort daq (userland/snort/pfring-daq-module)

still looks like snort try to instruct drop and traffic still flows...
its possible that snort drop action only drops the traffic from the daq and not from the ring itself?

**Comment by dotanalon** [comment] 2018-11-20 18:28
@cardigliano if its possible I suggest we perform a quick live session to debug this, it will rapid the process..

**Comment by dotanalon** [comment] 2018-11-21 06:42
@cardigliano 
Sorry, for some reason I recompiled and reinstalled the kernel module but the module that was loaded is diffrent:
root@ip-172-16-3-216:~# find /lib/modules/4.15.0-1027-aws/ -iname pf_ring.ko -exec md5sum {} \;
73a75607be3b34a4c3ecef5206250421  /lib/modules/4.15.0-1027-aws/updates/dkms/pf_ring.ko
1a9b432a4942152b6bf9138ae09f4d31  /lib/modules/4.15.0-1027-aws/kernel/net/pf_ring/pf_ring.ko

the module that was loaded by modprobe is the dkms one instead the net one...
after reloaded the right module its looks like snort integration working with the ICMP, Im continuing with my tests, will update if there is another issues
Thanks,

**Comment by dotanalon** [comment] 2018-11-21 06:52
@cardigliano 
please ignore the comment about wrong module.. (i deleted the comment), the issue still exists, the snort instruct drop but traffic flows..

**Comment by cardigliano** [comment] 2018-11-21 17:42
@dotanalon, as double check, please try running "pfcount -i eth0 -v 1 " vs "pfcount -i eth0 -v 1 -u 1", the second command inserts filtering rules for each received packet, this to make sure that filtering is working with your kernel module.
Also, could you try removing the fast-tx option to see if it makes any difference?

**Comment by dotanalon** [comment] 2018-11-26 07:10
@cardigliano 
the first execution looked OK no errors...

when running the second command (with the rule insertion), I got the following errors:
sudo pfcount -i eth0 -v 1 -u 1 > pfcount.2.log

Adding hash filtering rules
Dumping statistics on /proc/net/pf_ring/stats/27670-eth0.4
pfring_handle_hash_filtering_rule(1) failed
pfring_handle_hash_filtering_rule(1) failed
pfring_handle_hash_filtering_rule(1) failed
pfring_handle_hash_filtering_rule(1) failed
pfring_handle_hash_filtering_rule(1) failed
pfring_handle_hash_filtering_rule(1) failed
pfring_handle_hash_filtering_rule(1) failed
pfring_handle_hash_filtering_rule(1) failed
pfring_handle_hash_filtering_rule(1) failed
pfring_handle_hash_filtering_rule(1) failed
pfring_handle_hash_filtering_rule(1) failed
pfring_handle_hash_filtering_rule(1) failed
pfring_handle_hash_filtering_rule(1) failed
pfring_handle_hash_filtering_rule(1) failed
pfring_handle_hash_filtering_rule(1) failed
pfring_handle_hash_filtering_rule(1) failed
pfring_handle_hash_filtering_rule(1) failed
pfring_handle_hash_filtering_rule(1) failed
pfring_handle_hash_filtering_rule(1) failed
pfring_handle_hash_filtering_rule(1) failed
pfring_handle_hash_filtering_rule(1) failed

"=========================
Absolute Stats: [21 pkts total][0 pkts dropped][0.0% dropped]
[21 pkts rcvd][2'454 bytes rcvd]
========================="

in additional Im attaching 2 log files of the execution
[pfcount.2.log](https://github.com/ntop/PF_RING/files/2614416/pfcount.2.log)
[pfcount.1.log](https://github.com/ntop/PF_RING/files/2614417/pfcount.1.log)

**Comment by cardigliano** [comment] 2018-11-26 08:21
@dotanalon some pfring_handle_hash_filtering_rule failure is expected in case the application sets multiple rules for the same session (this happens due to queued packets), besides that, do you see that filtering is working? (you should notice a few received packets with respect to the pfcount without -u)

**Comment by dotanalon** [comment] 2018-11-26 08:30
@cardigliano 
no there is same packet count with both executions...
no need in some env var for passing the app the location of the flow table rules?

**Comment by cardigliano** [comment] 2018-11-26 08:30
Please provide "cat /proc/net/pf_ring/info"

**Comment by dotanalon** [comment] 2018-11-27 08:22
@cardigliano 
PF_RING Version          : 7.2.0 (7.2.0-stable:7106e9f85e5b16fc5de7a28edb919cd450d72198)
Total rings              : 0

Standard (non ZC) Options
Ring slots               : 4096
Slot version             : 17
Capture TX               : Yes [RX+TX]
IP Defragment            : No
Socket Mode              : Standard
Cluster Fragment Queue   : 0
Cluster Fragment Discard : 0

**Comment by cardigliano** [comment] 2018-11-27 15:42
@dotanalon your configuration looks fine, I ran pfcount with -u using the same configuration and it is working for me. Are you able to provide some pcap data (a few packets) to try to debug this issue in our lab?

**Comment by dotanalon** [comment] 2018-11-28 11:12
@cardigliano
see attached...
[pf_ring.pcap.gz](https://github.com/ntop/PF_RING/files/2624122/pf_ring.pcap.gz)

**Comment by cardigliano** [comment] 2018-11-28 11:53
I guess you were using pfcount with -u without -v, I just pushed a fix for that.
I replayed your pcap using pfsend at high rate, and this is the outcome on my machine:
- This is the pfcount output without filtering (pfcount -i eth0)
Actual Stats: [3'849'501 pkts rcvd][1'000.04 ms][3'849'343.17 pps][3.36 Gbps]
- This is the pfcount output *with* filtering (pfcount -i eth0 -u 1)
Actual Stats: [714'699 pkts rcvd][1'000.04 ms][714'667.55 pps][0.48 Gbps]
(This leaking traffic is ARP)

**Comment by dotanalon** [comment] 2018-11-28 13:55
@cardigliano 
this is exactly the reason I asked you to login to my env from the beginning..
the fact its working on your env and not working on my no surprising for anyone..
I dont really have something to do with this kind of situation beside stop the testing of PF_RING and move to different product...

**Comment by cardigliano** [comment] 2018-11-28 14:01
@dotanalon please note that filtering is working with your traffic (what is leaking is ARP traffic which is not supported by hash rules), the fix I pushed is for pfcount for injecting the correct tuple (packet parsing was disabled). Please let me know if you want to check it to see if you are still able to reproduce it (I am not against connecting to your machine if needed).

**Closed as completed** 2018-12-03 14:23 UTC
