### ISSUE TITLE
Unable to accept the data

### ISSUE THREAD

**Issue by strong46066999** [ntop/PF_RING#302] opened 2017-12-07 11:02 UTC
Configure PC A configuration
CPU: Intel (R) Xeon (R) CPU E5-1630 v3 @ 3.70GHz
Network card: i40e

PC B configuration
CPU: Intel (R) Xeon (R) CPU E5-2643 v4 @ 3.40GHz
Network card: i40e

Front:
Are loaded with PF_RING / drivers / intel / i40e / i40e-2.3.6-zc / src / load_driver.sh

step:
B ./zcount -i zc: eth3 -v
A ./zsend -i zc: eth0 -n 1

If you set -n 1 on A, B will not receive it。
Set at least -n 4， B will receive 4 packages
Do not know where the problem?

**Comment by cardigliano** [comment] 2017-12-07 11:05
Duplicate of #244

**Closed as completed by cardigliano** 2017-12-07 11:05 UTC
