### ISSUE TITLE
[PF RING FT] pfring_ft_license returns incorrect value [part2]

### ISSUE THREAD

**Issue by vitalivanov** [ntop/PF_RING#453] opened 2019-01-10 17:18 UTC
@cardigliano 
this is continuation of #450 

With latest PF RING FT and nDPI we have:
```sh
NTOP: PF_RING FT v.7.5.0.190108.
NTOP: SystemID: 3D9873D19206AAF2.
NTOP: License: Valid license.
```

Here is the backtrace:
```sh
(gdb) bt
#0  strlen () at ../sysdeps/x86_64/strlen.S:106
#1  0x000000000078df4e in ndpi_strdup (s=0x0) at ndpi_main.c:384
#2  0x000000000078e158 in ndpi_set_proto_defaults (ndpi_mod=0x23407c0, breed=NDPI_PROTOCOL_UNRATED, protoId=0, can_have_a_subprotocol=0 '\000', tcp_master_protoId=0x7fffffffd820, 
    udp_master_protoId=0x7ffff3e55f69, protoName=0x0, protoCategory=NDPI_PROTOCOL_CATEGORY_UNSPECIFIED, tcpDefPorts=0x7fffffffd860, udpDefPorts=0x7ffff3e44c67 <ndpi_init_detection_module+647>)
    at ndpi_main.c:552
#3  0x00007ffff3e44c8c in ndpi_init_protocol_defaults (ndpi_mod=0x23407c0) at ndpi_main.c:998
#4  ndpi_init_detection_module () at ndpi_main.c:2231
#5  0x00000000007bd482 in pfring_ft_dpi_alloc ()
#6  0x00000000007c0a0b in pfring_ft_create_table ()
```

**Comment by vitalivanov** [comment] 2019-01-10 17:26
But the PC doesn't have license installed.

**Comment by cardigliano** [comment] 2019-01-11 15:34
Duplicate of #450

**Closed as completed by cardigliano** 2019-01-11 15:34 UTC
