### ISSUE TITLE
Ethernet SDI Adapte Auto-Negotiation:"Not Available"

### ISSUE THREAD

**Issue by MaoPann** [ntop/PF_RING#622] opened 2020-08-14 08:41 UTC
After using fm10 driver in fm10420 adapter
![image](https://user-images.githubusercontent.com/44804599/90230818-b55eef80-de4c-11ea-8626-9e995cbf3a65.png)

**Comment by cardigliano** [comment] 2020-08-15 08:23
Duplicate of #620

**Closed as completed by cardigliano** 2020-08-15 08:23 UTC
