### ISSUE TITLE
dkms modules not recompiling automatically on kernel update

### ISSUE THREAD

**Issue by g1l3sp** [ntop/PF_RING#618] opened 2020-08-13 22:24 UTC
I'm noticing on our Ubuntu 20.04 boxes that when a kernel update happens, when the host restarts we are left without a working ixgbe zc driver.  I have to manually `dpkg-reconfigure ixgbe-zc-dkms` to get it to compile, and then restart the pf_ring service to get back to a working state.  

Is there something I'm missing in order to have this happen automatically, or is this a bug in one of the packages?  I'm using the stable repositories:

deb http://packages.ntop.org/apt-stable/20.04/ x64/
deb http://packages.ntop.org/apt-stable/20.04/ all/

A bit of system information:

```root@host: ~ # lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal

root@host: ~ # uname -a
Linux host 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

# Show all ntop packages installed on this host
root@host: ~ # aptitude search "?origin (ntop) ?installed"
i   ixgbe-zc-dkms                                                                                           - ixgbe-zc driver in DKMS format (http://www.ntop.org/pf_ring/).                                                   
i A ndpi                                                                                                    - A L7 DPI library.                                                                                                
i   nprobe                                                                                                  - A network probe.                                                                                                 
i A ntopng-data                                                                                             - Geolocation databases download helper for ntopng and other ntop software                                         
i A pfring                                                                                                  - PF_RING (http://www.ntop.org/pf_ring/) [7.6.0-stable:8c16c12278c9b3ed903bf9cd1ec8d0999fb1d8bc]                   
i A pfring-dkms                                                                                             - PF_RING driver in DKMS format. GIT info: 7.6.0-stable:2046ef03e71eebc8a69d972fbf4bb667aff03e85                   

root@host: ~ # apt-cache showpkg pfring ixgbe-zc-dkms 
Package: pfring
Versions: 
7.6.0-3116 (/var/lib/apt/lists/packages.ntop.org_apt-stable_20.04_x64_Packages)
 Description Language: 
                 File: /var/lib/apt/lists/packages.ntop.org_apt-stable_20.04_x64_Packages
                  MD5: f682af9b074b29c9992134a487595ba8
 Description Language: 
                 File: /var/lib/dpkg/status
                  MD5: f682af9b074b29c9992134a487595ba8

7.6.0-3103 (/var/lib/dpkg/status)
 Description Language: 
                 File: /var/lib/apt/lists/packages.ntop.org_apt-stable_20.04_x64_Packages
                  MD5: f682af9b074b29c9992134a487595ba8
 Description Language: 
                 File: /var/lib/dpkg/status
                  MD5: f682af9b074b29c9992134a487595ba8


Reverse Depends: 
  nprobe,pfring 7.6.0-3103
  pfring-dkms,pfring 7.6.0-3103
  pfring-dkms,pfring 7.6.0-3117
  cento,pfring 7.6.0-3116
  ntopng,pfring 7.6.0-3116
  nprobe,pfring 7.6.0-3116
  n2disk,pfring 7.6.0-3116
Dependencies: 
7.6.0-3116 - ndpi (5 3.2.0-2726) net-tools (0 (null)) kmod (0 (null)) ethtool (0 (null)) pciutils (0 (null)) pfring-dkms (5 7.6.0) 
7.6.0-3103 - ndpi (5 3.2.0-2710) net-tools (0 (null)) kmod (0 (null)) ethtool (0 (null)) pciutils (0 (null)) pfring-dkms (5 7.6.0) 
Provides: 
7.6.0-3116 - 
7.6.0-3103 - 
Reverse Provides: 
Package: ixgbe-zc-dkms
Versions: 
5.5.3.3117 (/var/lib/apt/lists/packages.ntop.org_apt-stable_20.04_all_Packages)
 Description Language: 
                 File: /var/lib/apt/lists/packages.ntop.org_apt-stable_20.04_all_Packages
                  MD5: 56d7732035b590feae58eb14a16e75a9
 Description Language: 
                 File: /var/lib/dpkg/status
                  MD5: 56d7732035b590feae58eb14a16e75a9

5.5.3.3103 (/var/lib/dpkg/status)
 Description Language: 
                 File: /var/lib/apt/lists/packages.ntop.org_apt-stable_20.04_all_Packages
                  MD5: 56d7732035b590feae58eb14a16e75a9
 Description Language: 
                 File: /var/lib/dpkg/status
                  MD5: 56d7732035b590feae58eb14a16e75a9


Reverse Depends: 
  pfring-drivers-zc-dkms,ixgbe-zc-dkms
Dependencies: 
5.5.3.3117 - dkms (2 1.95) 
5.5.3.3103 - dkms (2 1.95) 
Provides: 
5.5.3.3117 - 
5.5.3.3103 - 
Reverse Provides: 

root@host: ~ # ```

**Comment by cardigliano** [comment] 2020-08-14 07:57
This looks like a duplicate of #617

**Closed as completed** 2020-08-14 08:24 UTC
