### ISSUE TITLE
Some Skype flows are not detected

### ISSUE THREAD

**Issue by tansly** [ntop/PF_RING#484] opened 2019-06-12 15:36 UTC
Running `ftflow_pcap` on version `7.4.0-stable`, HEAD at 2a274a28ac1682c68bbfcd730889626feec74108

When a Skype call is made, some flows are detected as `Skype.SkypeCall`:
`[Flow] l7: Skype.SkypeCall, category: 10, srcIp: 192.168.6.10, dstIp: 104.44.200.121, srcPort: 50728, dstPort: 3478, protocol: 17, tcpFlags: 0x00, c2s: { Packets: 1, Bytes: 255, First: 1560351096.434030, Last: 1560351096.434030 }, s2c: { Packets: 23, Bytes: 4587, First: 1560351096.603031, Last: 1560351104.484547 }`
`[Flow] l7: Skype.SkypeCall, category: 10, srcIp: 192.168.6.10, dstIp: 104.44.200.121, srcPort: 58984, dstPort: 3478, protocol: 17, tcpFlags: 0x00, c2s: { Packets: 1, Bytes: 255, First: 1560351096.435731, Last: 1560351096.435731 }, s2c: { Packets: 1, Bytes: 195, First: 1560351096.614924, Last: 1560351096.614924 }`
`[Flow] l7: Skype.SkypeCall, category: 10, srcIp: 192.168.6.10, dstIp: 10.6.66.3, srcPort: 50728, dstPort: 24539, protocol: 17, tcpFlags: 0x00, c2s: { Packets: 1, Bytes: 154, First: 1560351098.653723, Last: 1560351098.653723 }, s2c: { Packets: 18, Bytes: 2748, First: 1560351099.55614, Last: 1560351104.464779 }`
`[Flow] l7: Skype.SkypeCall, category: 10, srcIp: 192.168.6.10, dstIp: 139.162.192.157, srcPort: 50728, dstPort: 24539, protocol: 17, tcpFlags: 0x00, c2s: { Packets: 2, Bytes: 308, First: 1560351098.710044, Last: 1560351099.50766 }, s2c: { Packets: 0, Bytes: 0, First: 0.0, Last: 0.0 }`

The thing is, we are working on an application blocker kind of thing; when these flows are detected as Skype calls, we make some configurations on the network to prevent them from passing through. (I don't think the details are relevant, but what we are doing is updating some tables of a P4 controlled switch.)

At this point, I expect the call to disconnect. But Skype reports poor connection for a few seconds, then the call continues. This does not always happen, though; sometimes the call actually disconnects. If it continues, I usually see a flow like the following:
`[Flow] l7: Unknown, category: 0, srcIp: 192.168.6.10, dstIp: 104.44.200.120, srcPort: 50728, dstPort: 3480, protocol: 17, tcpFlags: 0x00, c2s: { Packets: 974, Bytes: 148212, First: 1560351098.829983, Last: 1560351124.147524 }, s2c: { Packets: 912, Bytes: 129889, First: 1560351099.211332, Last: 1560351124.307533 }`
Judging by the IPs and ports (and my inspection of the attached pcap file), this is clearly a Skype call flow. Interestingly, `ndpiReader` can detect the same flow (in the same pcap) as a Skype call:
`
        1       UDP 192.168.6.10:50728 <-> 104.44.200.120:3480 [proto: 125.38/Skype.SkypeCall][cat: VoIP/10][974 pkts/148212 bytes <-> 912 pkts/129889 bytes]
`

pcap file of the experiment is attached.

[skype_unknown.zip](https://github.com/ntop/PF_RING/files/3281943/skype_unknown.zip)

**Comment by cardigliano** [comment] 2019-06-17 08:08
@tansly thank you for the pcap, we have been able to reproduce it, this is due to the (optimized) way FT is using nDPI for best performance, we will fix this asap!

**Comment by cardigliano** [comment] 2019-07-01 09:22
@tansly I just pushed a library update to fix Skype detection, please check it and let me know. Thank you.

**Comment by tansly** [comment] 2019-07-01 14:16
I tried and got interesting results. I'm comparing the results of the `dev` branch against `7.4.0-stable`, using the same pcap file.

The previously `Unknown` Skype call flow is now detected as `Skype.SkypeCall`:
`[Flow] l7: Skype.SkypeCall, category: 10, srcIp: 192.168.6.10, dstIp: 104.44.200.120, srcPort: 50728, dstPort: 3480, protocol: 17, tcpFlags: 0x00, c2s: { Packets: 974, Bytes: 148212, First: 1560351098.829983, Last: 1560351124.147524 }, s2c: { Packets: 912, Bytes: 129889, First: 1560351099.211332, Last: 1560351124.307533 }`

However, lots of other flows that used to be detected successfully are now `Unknown`. I'm attaching the output of both versions.

[dev.txt](https://github.com/ntop/PF_RING/files/3345993/dev.txt)
[stable.txt](https://github.com/ntop/PF_RING/files/3345994/stable.txt)

**Comment by cardigliano** [comment] 2019-07-01 17:06
@tansly I pushed another library update, please check it now. Thank you.

**Comment by tansly** [comment] 2019-07-01 17:30
There is some improvement, as most of the unknown flows are detected. But now the subprotocol of SSL flows are not shown. For example;
In 7.4.0-stable:
`
[Flow] l7: SSL.Facebook, category: 5, srcIp: 157.240.1.174, dstIp: 192.168.6.10, srcPort: 443, dstPort: 54884, protocol: 6, tcpFlags: 0x10, c2s: { Packets: 3, Bytes: 294, First: 1560351093.31246, Last: 1560351118.780672 }, s2c: { Packets: 0, Bytes: 0, First: 0.0, Last: 0.0 }
`
In dev:
`[Flow] l7: SSL, category: 0, srcIp: 157.240.1.174, dstIp: 192.168.6.10, srcPort: 443, dstPort: 54884, protocol: 6, tcpFlags: 0x10, c2s: { Packets: 3, Bytes: 294, First: 1560351093.31246, Last: 1560351118.780672 }, s2c: { Packets: 0, Bytes: 0, First: 0.0, Last: 0.0 }
`
The `Facebook` part disappeared. The same happened with other SSL flows as well (e.g. Google).

For Skype calls; a flow that used to be detected (in 7.4.0-stable) as Skype call is unknown now, but a previously unknown flow became detected as a Skype call.

In 7.4.0-stable:
`
[Flow] l7: Skype.SkypeCall, category: 10, srcIp: 192.168.6.10, dstIp: 139.162.192.157, srcPort: 50728, dstPort: 24539, protocol: 17, tcpFlags: 0x00, c2s: { Packets: 2, Bytes: 308, First: 1560351098.710044, Last: 1560351099.50766 }, s2c: { Packets: 0, Bytes: 0, First: 0.0, Last: 0.0 }
`
`
[Flow] l7: Unknown, category: 0, srcIp: 192.168.6.10, dstIp: 104.44.200.120, srcPort: 50728, dstPort: 3480, protocol: 17, tcpFlags: 0x00, c2s: { Packets: 974, Bytes: 148212, First: 1560351098.829983, Last: 1560351124.147524 }, s2c: { Packets: 912, Bytes: 129889, First: 1560351099.211332, Last: 1560351124.307533 }
`

In dev:
`
[Flow] l7: Unknown, category: 0, srcIp: 192.168.6.10, dstIp: 139.162.192.157, srcPort: 50728, dstPort: 24539, protocol: 17, tcpFlags: 0x00, c2s: { Packets: 2, Bytes: 308, First: 1560351098.710044, Last: 1560351099.50766 }, s2c: { Packets: 0, Bytes: 0, First: 0.0, Last: 0.0 }
`
`
[Flow] l7: Skype.SkypeCall, category: 10, srcIp: 192.168.6.10, dstIp: 104.44.200.120, srcPort: 50728, dstPort: 3480, protocol: 17, tcpFlags: 0x00, c2s: { Packets: 974, Bytes: 148212, First: 1560351098.829983, Last: 1560351124.147524 }, s2c: { Packets: 912, Bytes: 129889, First: 1560351099.211332, Last: 1560351124.307533 }
`

Output of `ftflow_pcap`:
[dev_4f20d1a9edde6a415a0b7a141c70a44c8a1110e8.txt](https://github.com/ntop/PF_RING/files/3346708/dev_4f20d1a9edde6a415a0b7a141c70a44c8a1110e8.txt)

Thanks.

**Comment by cardigliano** [comment] 2019-07-02 09:08
@tansly it seems that the subprotocol for SSL is working for me, did you also install latest ndpi?
Could you share the pcap you are using to reproduce it? Thank you.

**Comment by tansly** [comment] 2019-07-02 10:04
I'm using the pcap from my original post: https://github.com/ntop/PF_RING/files/3281943/skype_unknown.zip

I've compiled and installed latest nDPI from the `dev` branch.

I'm running `./ftflow_pcap -7 -i skype_unknown.pcap`, and this is the output I get: [dev.txt](https://github.com/ntop/PF_RING/files/3349458/dev.txt)
There are some SSL flows with subprotocols detected, e.g. SSL.Skype flows. However the first few flows that used to be (using 7.4.0-stable) detected as SSL.Facebook, SSL.Google, SSL.Whatsapp are now just SSL.

Thanks.

**Comment by cardigliano** [comment] 2019-07-03 07:41
@tansly detection of SSL subprotocols has been fixed, this also required a patch in nDPI, please update both FT and nDPI. Thank you.

**Comment by tansly** [comment] 2019-07-03 09:15
It seems alright, thanks!

**Comment by cardigliano** [comment] 2019-07-03 09:18
Great, thank you, let's close this then.

**Closed as completed by cardigliano** 2019-07-03 09:18 UTC
