### ISSUE TITLE
Ubuntu 14.04.3 with kernel 3.19.0 carsh

### ISSUE THREAD

**Issue by laoyang103** [ntop/PF_RING#219] opened 2017-05-24 08:44 UTC
I use PF_RING-6.4.1 release version, run with a libpcap based application named ipmtube
I use ixgbe-4.1.5-zc in driver directory,  my NIC is 82599ES 10-Gigabit SFI/SFP
When I run the application all is OK, but after one week the kernel crash.

the follow is my kern.log dmesg ... link

https://github.com/laoyang103/simplebtm/tree/master/carsh

the follow is my environment：

**cat /etc/issue**
Ubuntu 14.04.3 LTS \n \l

**uname -a**
Linux localhost 3.19.0-25-generic #26~14.04.1-Ubuntu SMP Fri Jul 24 21:16:20 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

 **lspci | grep Eth**
02:00.0 Ethernet controller: Intel Corporation 82599ES 10-Gigabit SFI/SFP+ Network Connection (rev 01)
02:00.1 Ethernet controller: Intel Corporation 82599ES 10-Gigabit SFI/SFP+ Network Connection (rev 01)

**Comment by cardigliano** [comment] 2017-05-24 09:15
@laoyang103 could you provide the trace of the crash? I do not see the crash at the end of your log files, sorry.

**Comment by laoyang103** [comment] 2017-05-25 01:16
@cardigliano trace is not at end of log file
in kern.log line 30 to line 2000(May 22 15:23:35 - May 22 15:24:09), the kernel crash during this Period of time.
in kern.log.1 line 2758 to line 2958(May 15 16:27:32 - May 15 16:37:09 ), the kernel crash during this Period of time.

**Comment by cardigliano** [comment] 2017-05-25 17:33
@laoyang103 do you know what ipmtube is? I see memory allocation failures.

**Comment by laoyang103** [comment] 2017-05-26 01:38
@cardigliano it is a libpcap based application, I replace libpcap.so with userland libpcap-1.7.4, and start it with **ipmtube  zc:p1p1**, so that ipmtube can use ZC to get packet from NIC.

When a packet coming, I use malloc get a memory to store the packet, process and free it.
I search the follow error: 
[278214.235308] ipmtube: page allocation failure: order:0, mode:0x20
and I got https://www.cyberciti.biz/faq/linux-page-allocation-failure-erro/

It say "This error related to memory fragmentation",  so I think when the process 10Gbps traffic it will malloc memory frequent and generate memory fragmentation

**Comment by cardigliano** [comment] 2017-05-26 07:43
How much memory do you have in this system?
Please provide "cat /proc/meminfo" and "ifconfig -a"

**Comment by laoyang103** [comment] 2017-05-26 07:46
**cat /proc/meminfo**
```
MemTotal:       32901400 kB
MemFree:        16552704 kB
MemAvailable:   18385220 kB
Buffers:          140460 kB
Cached:          1822468 kB
SwapCached:            0 kB
Active:          2716884 kB
Inactive:        1590548 kB
Active(anon):    2345540 kB
Inactive(anon):      824 kB
Active(file):     371344 kB
Inactive(file):  1589724 kB
Unevictable:           0 kB
Mlocked:               0 kB
SwapTotal:      62498812 kB
SwapFree:       62498812 kB
Dirty:              3940 kB
Writeback:             0 kB
AnonPages:       2345700 kB
Mapped:          1220508 kB
Shmem:               840 kB
Slab:             256116 kB
SReclaimable:      80784 kB
SUnreclaim:       175332 kB
KernelStack:        7200 kB
PageTables:        21944 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:    73706632 kB
Committed_AS:    4707912 kB
VmallocTotal:   34359738367 kB
VmallocUsed:      392164 kB
VmallocChunk:   34359331876 kB
HardwareCorrupted:     0 kB
AnonHugePages:   1781760 kB
CmaTotal:              0 kB
CmaFree:               0 kB
HugePages_Total:    5120
HugePages_Free:     4776
HugePages_Rsvd:      289
HugePages_Surp:        0
Hugepagesize:       2048 kB
DirectMap4k:       94204 kB
DirectMap2M:    33413120 kB
```

```

**Comment by laoyang103** [comment] 2017-05-29 08:35
@cardigliano
Hi cardigliano, 
is there a result about https://github.com/ntop/PF_RING/issues/219

**Comment by cardigliano** [comment] 2017-05-29 10:00
@laoyang103 as you noticed this seems to be related to memory allocation failures caused by memory exhaustion, then the driver is not able to find memory when trying to allocate rx buffers in kernel space. Please note ZC does not requires kernel space buffers, however it seems your application is closing and opening interface p1p1 every 1-5 minutes, this means the interface comes back to kernel mode often, requiring kernel buffers allocation. You can notice a lot of "left promiscuous mode" / "entered promiscuous mode" messages.

**Comment by laoyang103** [comment] 2017-05-29 11:03
@cardigliano
very thanks for your reply, I will try you say,

**Comment by cardigliano** [comment] 2017-05-31 11:28
Please reopen if necessary

**Closed as completed by cardigliano** 2017-05-31 11:28 UTC

**Comment by laoyang103** [comment] 2017-06-02 11:10
OK
