### ISSUE TITLE
Suricata and ntop PF_RING: IPS mode doesn't work

### ISSUE THREAD

**Issue by rdpmc** [ntop/PF_RING#100] opened 2016-05-31 16:10 UTC
Hello
Why suricata in  --pfring mode  can't block packet, so only works in IDS mode, not in IPS.
Is it possible to run suricata in IPS mode with ntop pfring ?
I built pfring module and userland (without binary libraries in "libs" dir) and suricata supports pfring and run well. But it only alerts on drop rule (wDrop), not drop.
Thanks.

**Comment by cardigliano** [comment] 2016-06-01 08:44
Hi
PF_RING IPS support in suricata is available at https://github.com/cardigliano/suricata/tree/dev-pfring but never merged mainstream
in essence this is the IPS patch https://github.com/cardigliano/suricata/commit/0df4ed10daf3fc2612f09a55b9a8d6f98f6b8f64 , at the very bottom you can see the suricata.yaml.in with the configuration example.

Alfredo

**Closed as completed** 2016-06-01 16:30 UTC

**Comment by rdpmc** [comment] 2016-06-03 10:50
Thanks. I've tried it, using ping, and it is not blocks it (wDrop).

My config part concerning pf-ring:

pfring:
- interface: default
  
  cluster-id: 1
  
  cluster-type: cluster_flow
- interface: ethernet0
  
  copy-iface: ethernet2
  
  copy-mode: ips
- interface: ethernet2
  
  copy-iface: ethernet0
  
  copy-mode: ips

runmode: workers

In log thereis all ok ,some info from log:

PF_RING IPS activeted on eth0-->eth2
Enabling zero-copy for eth0
PF_RING IPS activeted on eth2-->eth0
Enabling zero-copy for eth2

And in alert log: only wDrop, while my rule has "drop" action. And ping is going through eth2-eth0

**Comment by cardigliano** [comment] 2016-06-03 11:00
In essence inline mode is working now and forwarding packets, but the problem is that it does not drop packets, correct? Are you sure this is related to pf_ring? Did you try the same ocnfiguration with af_packet or other modules?

Alfredo

**Comment by Onotoko** [comment] 2019-09-05 04:19
Hello you guys,
I tried with run suricata and pfring in IPS mode, but it cannot forward packet. Any body can help me?
```
pfring:
  - interface: eth2
    cluster-id: 99
    cluster-type: cluster_flow
    copy-iface: eth1
    copy-mode: ips
    checksum-checks: yes
  # Second interface
  - interface: eth1
    cluster-id: 98
    copy-iface: eth2
    copy-mode: ips
    cluster-type: cluster_flow
    checksum-checks: yes
```
Thanks!

**Comment by cardigliano** [comment] 2019-09-05 07:10
@Onotoko please note that IPS mode with pf_ring in Suricata requires some patch (please see https://github.com/ntop/PF_RING/issues/100#issuecomment-222930397), did you use it? However please note that we cannot provide support for it as the patch has never been approved..

**Comment by Onotoko** [comment] 2019-09-05 09:09
@cardigliano,
I tried  #100 (comment) but I got error when complied it on centos 7 with PF_RING Version : 7.5.0 
```
checking for capng_clear in -lcap-ng... no

   WARNING!  libcap-ng library not found, go get it
   from http://people.redhat.com/sgrubb/libcap-ng/
   or your distribution:

   Ubuntu: apt-get install libcap-ng-dev
   Fedora: yum install libcap-ng-devel

   Suricata will be built without support for dropping privs.

checking for libnspr... yes
checking nspr.h usability... yes
checking nspr.h presence... yes
checking for nspr.h... yes
checking for PR_GetCurrentThread in -lnspr4... no

   ERROR!  libnspr library not found, go get it
   from Mozilla or your distribution:

   Ubuntu: apt-get install libnspr4-dev
   Fedora: yum install nspr-devel

```

I installed those, but it cannot help solve problem. Do you have any idea?
