### ISSUE TITLE
Kernel panic on 6.0.2

### ISSUE THREAD

**Issue by zambo99** [ntop/PF_RING#50] opened 2015-11-09 16:41 UTC
PF_RING (vanilla) version 6.0.2 causes a kernel panic when capturing live data on Linux. The panic happened when using it with kernel version 3.13.11.4.

The kernel panic seems not to be related to any particular operation (i.e., inserting the kernel module, removing the module or bringing a network interface up or down), it just happens out of the blue.

Release notes of PF_RING 6.0.3 give no indication that a new release fixes the issue.

![pf-ring-kernel-panic](https://cloud.githubusercontent.com/assets/15734924/11039649/05d40522-8709-11e5-9e6f-e3f43f2638fa.jpg)
.

**Comment by zambo99** [comment] 2015-11-19 15:09
Hi, any news about this issue?

**Comment by cardigliano** [comment] 2015-11-19 18:09
We've been not able to reproduce it so far, still investigating..

**Comment by cardigliano** [comment] 2016-01-27 22:09
It did not reproduce on latest stable (6.2) so far, closing the issue for now.

**Closed as completed by cardigliano** 2016-01-27 22:09 UTC
